version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:81
    depends_on: 
      - php
    links:
      - php
  
  php:
    container_name: php
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./server:/var/www/html
    depends_on: 
      - mysql
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    build:
      context: docker/mysql
    environment:
      MYSQL_DATABASE: laravel-graphql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "13307:3306"
    volumes: 
      - .docker/mysql:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d 
